server:
  port: 10001

eureka:
  client:
    # 是否从其他的服务中心同步服务列表
    fetch-registry: true
    # 是否把自己作为服务注册到其他服务注册中心
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:10002/eureka,http://localhost:10003/eureka

spring:
  application:
    name: @pom.artifactId@