server:
  port: 10110
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10001/eureka/,http://localhost:10002/eureka/,http://localhost:10003/eureka/

spring:
  application:
    name: server-monitor
