spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zhengbinger/config-center
          search-paths: '{application}'
          username: zhengbinger
          password: Zb@123456