server:
  port: 12000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10009/eureka/

spring:
  application:
    name: @pom.artifactId@
  cloud:
    config:
      uri: http://localhost:11000/
